sudo: required
services:
  - docker

before_install:
  - docker build -t pinkykitten/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pinkykitten/docker-react npm run test -- --coverage 
